# Day 8 - Data Preprocessing

## Objectives
- Prepare the dataset for Machine Learning
- Encode categorical variables
- Scale numerical features
- Separate features and target variable
- Save the processed dataset

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

pd.set_option("display.max_columns",None)

In [2]:
df = pd.read_csv("C:\\Users\\pushp\\OneDrive\\Desktop\\AI &ML project\\student-score-prediction-1\\data\\StudentPerformanceFactors.csv")

df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Study_Efficiency,Academic_Consistency,Healthy_Lifestyle_Index
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67,19.32,70.0,5.0
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61,12.16,60.0,6.0
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74,23.52,82.5,5.5
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71,25.81,84.5,6.0
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70,17.48,67.5,5.0

In [3]:
numerical_columns = df.select_dtypes(include=np.number).columns.tolist()
categorical_columns = df.select_dtypes(include="object").columns.tolist()
print("Numerical Columns :",numerical_columns)
print("\nCategorical Columns :",categorical_columns)

Numerical Columns : ['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores', 'Tutoring_Sessions', 'Physical_Activity', 'Exam_Score', 'Study_Efficiency', 'Academic_Consistency', 'Healthy_Lifestyle_Index']

Categorical Columns : ['Parental_Involvement', 'Access_to_Resources', 'Extracurricular_Activities', 'Motivation_Level', 'Internet_Access', 'Family_Income', 'Teacher_Quality', 'School_Type', 'Peer_Influence', 'Learning_Disabilities', 'Parental_Education_Level', 'Distance_from_Home', 'Gender']

In [4]:
label_encoders = {}

for column in categorical_columns:
    encoder = LabelEncoder()
    df[column] = encoder.fit_transform(df[column])
    label_encoders[column] = encoder

print("Encoding completed successfully!")

Encoding completed successfully!

In [5]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Study_Efficiency,Academic_Consistency,Healthy_Lifestyle_Index
0,23,84,1,0,0,7,73,1,1,0,1,2,1,2,3,0,1,2,1,67,19.32,70.0,5.0
1,19,64,1,2,0,8,59,1,1,2,2,2,1,0,4,0,0,1,0,61,12.16,60.0,6.0
2,24,98,2,2,1,7,91,2,1,2,2,2,1,1,4,0,2,2,1,74,23.52,82.5,5.5
3,29,89,1,2,1,8,98,2,1,1,2,2,1,0,4,0,1,1,1,71,25.81,84.5,6.0
4,19,92,2,2,1,6,65,2,1,3,2,0,1,1,4,0,0,2,0,70,17.48,67.5,5.0

In [6]:
target = "Exam_Score"

X = df.drop(columns = [target])
Y = df[target]

print("Feature Matrix Shape:",X.shape)
print("Target Shape :",Y.shape)

Feature Matrix Shape: (6607, 22)
Target Shape : (6607,)

In [7]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(
    X_scaled,
    columns = X.columns
)

X_scaled.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Study_Efficiency,Academic_Consistency,Healthy_Lifestyle_Index
0,0.504942,0.348375,-0.254249,-1.380517,-1.214685,-0.019796,-0.143800,-0.393061,0.285825,-1.213934,-0.284883,0.742375,0.661006,1.070550,0.031411,-0.342867,0.103120,0.717316,0.855746,0.627550,-0.148226,0.001856
1,-0.162822,-1.383736,-0.254249,0.913804,-1.214685,0.661399,-1.116110,-0.393061,0.285825,0.411451,1.062448,0.742375,0.661006,-1.575587,1.001199,-0.342867,-1.248688,-0.742280,-1.168570,-0.713283,-1.433691,1.116901
2,0.671882,1.560853,0.901062,0.913804,0.823259,-0.019796,1.106313,0.884966,0.285825,0.411451,1.062448,0.742375,0.661006,-0.252518,1.001199,-0.342867,1.454927,0.717316,0.855746,1.414073,1.458605,0.559379
3,1.506587,0.781403,-0.254249,0.913804,0.823259,0.661399,1.592469,0.884966,0.285825,-0.401242,1.062448,0.742375,0.661006,-1.575587,1.001199,-0.342867,0.103120,-0.742280,0.855746,1.842914,1.715698,1.116901
4,-0.162822,1.041220,0.901062,0.913804,0.823259,-0.700990,-0.699406,0.884966,0.285825,1.224144,1.062448,-1.450726,0.661006,-0.252518,1.001199,-0.342867,-1.248688,0.717316,-1.168570,0.282978,-0.469593,0.001856

In [8]:
X_scaled.describe().T

,count,mean,std,min,25%,50%,75%,max
Hours_Studied,6607.0,-1.161474e-16,1.000076,-3.167760,-0.663645,0.004119,0.671882,4.010702
Attendance,6607.0,-3.089199e-16,1.000076,-1.730158,-0.864103,0.001953,0.868009,1.734065
Parental_Involvement,6607.0,2.823028e-17,1.000076,-1.409559,-1.409559,0.901062,0.901062,0.901062
Access_to_Resources,6607.0,-2.688598e-18,1.000076,-1.380517,-1.380517,0.913804,0.913804,0.913804
Extracurricular_Activities,6607.0,1.312036e-16,1.000076,-1.214685,-1.214685,0.823259,0.823259,0.823259
Sleep_Hours,6607.0,-2.016449e-16,1.000076,-2.063380,-0.700990,-0.019796,0.661399,2.023788
Previous_Scores,6607.0,2.048712e-16,1.000076,-1.741167,-0.838307,-0.004898,0.897961,1.731370
Motivation_Level,6607.0,-2.054089e-16,1.000076,-1.671088,-0.393061,0.884966,0.884966,0.884966
Internet_Access,6607.0,-8.818602e-17,1.000076,-3.498640,0.285825,0.285825,0.285825,0.285825
Tutoring_Sessions,6607.0,7.850707e-17,1.000076,-1.213934,-0.401242,-0.401242,0.411451,5.287608
Family_Income,6607.0,-4.194213e-17,1.000076,-1.632214,-0.284883,-0.284883,1.062448,1.062448
Teacher_Quality,6607.0,3.656494e-17,1.000076,-1.450726,-1.450726,0.742375,0.742375,1.838925
School_Type,6607.0,1.226001e-16,1.000076,-1.512845,-1.512845,0.661006,0.661006,0.661006
Peer_Influence,6607.0,-8.280882e-17,1.000076,-1.575587,-0.252518,-0.252518,1.070550,1.070550
Physical_Activity,6607.0,-1.720703e-17,1.000076,-2.877953,-0.938377,0.031411,1.001199,2.940776
Learning_Disabilities,6607.0,-1.989563e-17,1.000076,-0.342867,-0.342867,-0.342867,-0.342867,2.916586
Parental_Education_Level,6607.0,1.882019e-17,1.000076,-1.248688,-1.248688,0.103120,0.103120,2.806734
Distance_from_Home,6607.0,5.807372e-17,1.000076,-2.201875,-0.742280,0.717316,0.717316,2.176912
Gender,6607.0,8.065795e-18,1.000076,-1.168570,-1.168570,0.855746,0.855746,0.855746
Study_Efficiency,6607.0,1.139966e-16,1.000076,-2.861238,-0.698302,-0.040994,0.642532,4.093867
Academic_Consistency,6607.0,-1.075439e-16,1.000076,-2.140697,-0.855232,-0.019680,0.815872,3.451075
Healthy_Lifestyle_Index,6607.0,-2.021826e-16,1.000076,-3.343276,-0.555666,0.001856,0.559379,3.346989

In [9]:
processed_df = X_scaled.copy()
processed_df[target] = Y.values
processed_df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Study_Efficiency,Academic_Consistency,Healthy_Lifestyle_Index,Exam_Score
0,0.504942,0.348375,-0.254249,-1.380517,-1.214685,-0.019796,-0.143800,-0.393061,0.285825,-1.213934,-0.284883,0.742375,0.661006,1.070550,0.031411,-0.342867,0.103120,0.717316,0.855746,0.627550,-0.148226,0.001856,67
1,-0.162822,-1.383736,-0.254249,0.913804,-1.214685,0.661399,-1.116110,-0.393061,0.285825,0.411451,1.062448,0.742375,0.661006,-1.575587,1.001199,-0.342867,-1.248688,-0.742280,-1.168570,-0.713283,-1.433691,1.116901,61
2,0.671882,1.560853,0.901062,0.913804,0.823259,-0.019796,1.106313,0.884966,0.285825,0.411451,1.062448,0.742375,0.661006,-0.252518,1.001199,-0.342867,1.454927,0.717316,0.855746,1.414073,1.458605,0.559379,74
3,1.506587,0.781403,-0.254249,0.913804,0.823259,0.661399,1.592469,0.884966,0.285825,-0.401242,1.062448,0.742375,0.661006,-1.575587,1.001199,-0.342867,0.103120,-0.742280,0.855746,1.842914,1.715698,1.116901,71
4,-0.162822,1.041220,0.901062,0.913804,0.823259,-0.700990,-0.699406,0.884966,0.285825,1.224144,1.062448,-1.450726,0.661006,-0.252518,1.001199,-0.342867,-1.248688,0.717316,-1.168570,0.282978,-0.469593,0.001856,70

In [10]:
processed_df.to_csv("C:\\Users\\pushp\\OneDrive\\Desktop\\AI &ML project\\student-score-prediction-1\\data\\student_performance_processed.csv",index = False)

print("processed dataset saved successfully!")

processed dataset saved successfully!

In [11]:
print("="*50)
print("Processed Dataset Shape : ",processed_df.shape)

display(processed_df.head())
display(processed_df.describe().T)

==================================================
Processed Dataset Shape :  (6607, 23)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Study_Efficiency,Academic_Consistency,Healthy_Lifestyle_Index,Exam_Score
0,0.504942,0.348375,-0.254249,-1.380517,-1.214685,-0.019796,-0.143800,-0.393061,0.285825,-1.213934,-0.284883,0.742375,0.661006,1.070550,0.031411,-0.342867,0.103120,0.717316,0.855746,0.627550,-0.148226,0.001856,67
1,-0.162822,-1.383736,-0.254249,0.913804,-1.214685,0.661399,-1.116110,-0.393061,0.285825,0.411451,1.062448,0.742375,0.661006,-1.575587,1.001199,-0.342867,-1.248688,-0.742280,-1.168570,-0.713283,-1.433691,1.116901,61
2,0.671882,1.560853,0.901062,0.913804,0.823259,-0.019796,1.106313,0.884966,0.285825,0.411451,1.062448,0.742375,0.661006,-0.252518,1.001199,-0.342867,1.454927,0.717316,0.855746,1.414073,1.458605,0.559379,74
3,1.506587,0.781403,-0.254249,0.913804,0.823259,0.661399,1.592469,0.884966,0.285825,-0.401242,1.062448,0.742375,0.661006,-1.575587,1.001199,-0.342867,0.103120,-0.742280,0.855746,1.842914,1.715698,1.116901,71
4,-0.162822,1.041220,0.901062,0.913804,0.823259,-0.700990,-0.699406,0.884966,0.285825,1.224144,1.062448,-1.450726,0.661006,-0.252518,1.001199,-0.342867,-1.248688,0.717316,-1.168570,0.282978,-0.469593,0.001856,70

,count,mean,std,min,25%,50%,75%,max
Hours_Studied,6607.0,-1.161474e-16,1.000076,-3.167760,-0.663645,0.004119,0.671882,4.010702
Attendance,6607.0,-3.089199e-16,1.000076,-1.730158,-0.864103,0.001953,0.868009,1.734065
Parental_Involvement,6607.0,2.823028e-17,1.000076,-1.409559,-1.409559,0.901062,0.901062,0.901062
Access_to_Resources,6607.0,-2.688598e-18,1.000076,-1.380517,-1.380517,0.913804,0.913804,0.913804
Extracurricular_Activities,6607.0,1.312036e-16,1.000076,-1.214685,-1.214685,0.823259,0.823259,0.823259
Sleep_Hours,6607.0,-2.016449e-16,1.000076,-2.063380,-0.700990,-0.019796,0.661399,2.023788
Previous_Scores,6607.0,2.048712e-16,1.000076,-1.741167,-0.838307,-0.004898,0.897961,1.731370
Motivation_Level,6607.0,-2.054089e-16,1.000076,-1.671088,-0.393061,0.884966,0.884966,0.884966
Internet_Access,6607.0,-8.818602e-17,1.000076,-3.498640,0.285825,0.285825,0.285825,0.285825
Tutoring_Sessions,6607.0,7.850707e-17,1.000076,-1.213934,-0.401242,-0.401242,0.411451,5.287608
Family_Income,6607.0,-4.194213e-17,1.000076,-1.632214,-0.284883,-0.284883,1.062448,1.062448
Teacher_Quality,6607.0,3.656494e-17,1.000076,-1.450726,-1.450726,0.742375,0.742375,1.838925
School_Type,6607.0,1.226001e-16,1.000076,-1.512845,-1.512845,0.661006,0.661006,0.661006
Peer_Influence,6607.0,-8.280882e-17,1.000076,-1.575587,-0.252518,-0.252518,1.070550,1.070550
Physical_Activity,6607.0,-1.720703e-17,1.000076,-2.877953,-0.938377,0.031411,1.001199,2.940776
Learning_Disabilities,6607.0,-1.989563e-17,1.000076,-0.342867,-0.342867,-0.342867,-0.342867,2.916586
Parental_Education_Level,6607.0,1.882019e-17,1.000076,-1.248688,-1.248688,0.103120,0.103120,2.806734
Distance_from_Home,6607.0,5.807372e-17,1.000076,-2.201875,-0.742280,0.717316,0.717316,2.176912
Gender,6607.0,8.065795e-18,1.000076,-1.168570,-1.168570,0.855746,0.855746,0.855746
Study_Efficiency,6607.0,1.139966e-16,1.000076,-2.861238,-0.698302,-0.040994,0.642532,4.093867
Academic_Consistency,6607.0,-1.075439e-16,1.000076,-2.140697,-0.855232,-0.019680,0.815872,3.451075
Healthy_Lifestyle_Index,6607.0,-2.021826e-16,1.000076,-3.343276,-0.555666,0.001856,0.559379,3.346989
Exam_Score,6607.0,6.723566e+01,3.890456,55.000000,65.000000,67.000000,69.000000,101.000000