# 🚀Day 7 - Feature Engineering & Feature Selection

## Objectives
- Understand the importance of features in Machine Learning.
- Select relevant features for prediction.
- Create new meaningful features.
- Analyze feature relationships.
- Prepare the dataset for preprocessing and model training.

##Topics
- Feature Selection
- Feature Engineering
- Feature Importance
- Correlation Analysis
- Creating New Features

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
df = pd.read_csv("C:\\Users\\pushp\\OneDrive\\Desktop\\AI &ML project\\student-score-prediction-1\\data\\StudentPerformanceFactors.csv")

In [4]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [ ]:
#Dataset overview
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

display(df.head())

Rows    : 6607
Columns : 20

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [6]:
#Identify Target & Features

target = "Exam_Score"
X = df.drop(columns = [target])
Y = df[target]

print("Target Variable : ", target)
print("Number of Features : ", X.shape[1])

Target Variable :  Exam_Score
Number of Features :  19

In [7]:
#categorize Features

numerical_features = X.select_dtypes(include=np.number).columns.tolist()
categorical_features = X.select_dtypes(include = "object").columns.tolist()


print("Numerical Features :")
print(numerical_features)

print("\nCategorical_features : ")
print(categorical_features)

Numerical Features :
['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores', 'Tutoring_Sessions', 'Physical_Activity']

Categorical_features :
['Parental_Involvement', 'Access_to_Resources', 'Extracurricular_Activities', 'Motivation_Level', 'Internet_Access', 'Family_Income', 'Teacher_Quality', 'School_Type', 'Peer_Influence', 'Learning_Disabilities', 'Parental_Education_Level', 'Distance_from_Home', 'Gender']

In [ ]:
#correlation with Target
correlation = df.corr(numeric_only = True)
correlation["Exam_Score"].sort_values(ascending=False)

Exam_Score           1.000000
Attendance           0.581072
Hours_Studied        0.445455
Previous_Scores      0.175079
Tutoring_Sessions    0.156525
Physical_Activity    0.027824
Sleep_Hours         -0.017022
Name: Exam_Score, dtype: float64

In [ ]:
#Create New Features
#study efficiency
df["Study_Efficiency"] = (
    df["Hours_Studied"] * df["Attendance"]
) / 100

In [ ]:
#Academic consistency
df["Academic_Consistency"] = (
    df["Previous_Scores"] + df["Exam_Score"]
) /2

In [ ]:
#healthy lifestyle index
df["Healthy_Lifestyle_Index"] = (
    df["Sleep_Hours"] + df["Physical_Activity"]
)/2

In [13]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Study_Efficiency,Academic_Consistency,Healthy_Lifestyle_Index
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67,19.32,70.0,5.0
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61,12.16,60.0,6.0
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74,23.52,82.5,5.5
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71,25.81,84.5,6.0
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70,17.48,67.5,5.0

In [ ]:
#Correlation After Feature Engineering
corr = df.corr(numeric_only= True)

corr["Exam_Score"].sort_values(ascending=False)

Exam_Score                 1.000000
Study_Efficiency           0.651652
Attendance                 0.581072
Hours_Studied              0.445455
Academic_Consistency       0.412060
Previous_Scores            0.175079
Tutoring_Sessions          0.156525
Physical_Activity          0.027824
Healthy_Lifestyle_Index    0.002065
Sleep_Hours               -0.017022
Name: Exam_Score, dtype: float64

In [ ]:
#Check for Constant Columns

constant_columns = [
    col for col in df.columns
    if df[col].nunique() == 1
]

print("Constant Columns:")
print(constant_columns)

Constant Columns:
[]

In [ ]:
#Check Unique Values
for col in categorical_features:
    print("=" * 50)
    print(f"{col}")
    print(df[col].value_counts())

==================================================
Parental_Involvement
Parental_Involvement
Medium    3362
High      1908
Low       1337
Name: count, dtype: int64
==================================================
Access_to_Resources
Access_to_Resources
Medium    3319
High      1975
Low       1313
Name: count, dtype: int64
==================================================
Extracurricular_Activities
Extracurricular_Activities
Yes    3938
No     2669
Name: count, dtype: int64
==================================================
Motivation_Level
Motivation_Level
Medium    3351
Low       1937
High      1319
Name: count, dtype: int64
==================================================
Internet_Access
Internet_Access
Yes    6108
No      499
Name: count, dtype: int64
==================================================
Family_Income
Family_Income
Low       2672
Medium    2666
High      1269
Name: count, dtype: int64
==================================================
Teacher_Quality
Teacher_Quality
Medium    3925
High      1947
Low        657
Name: count, dtype: int64
==================================================
School_Type
School_Type
Public     4598
Private    2009
Name: count, dtype: int64
==================================================
Peer_Influence
Peer_Influence
Positive    2638
Neutral     2592
Negative    1377
Name: count, dtype: int64
==================================================
Learning_Disabilities
Learning_Disabilities
No     5912
Yes     695
Name: count, dtype: int64
==================================================
Parental_Education_Level
Parental_Education_Level
High School     3223
College         1989
Postgraduate    1305
Name: count, dtype: int64
==================================================
Distance_from_Home
Distance_from_Home
Near        3884
Moderate    1998
Far          658
Name: count, dtype: int64
==================================================
Gender
Gender
Male      3814
Female    2793
Name: count, dtype: int64

In [ ]:
#saved Updated Dataset
df.to_csv("C:\\Users\\pushp\\OneDrive\\Desktop\\AI &ML project\\student-score-prediction-1\\data\\StudentPerformanceFactors.csv",index=False)
print("Feature engineered dataset saved successfully")

Feature engineered dataset saved successfully

# ✅ Conclusion

Today, I performed Feature Engineering and Feature Selection on the student performance dataset.

### Tasks Completed

✅ Identified target and feature variables

✅ Classified numerical and categorical features

✅ Analyzed feature correlations

✅ Created new meaningful features

- Study_Efficiency
- Academic_Consistency
- Healthy_Lifestyle_Index

✅ Checked constant columns

✅ Prepared the dataset for preprocessing

The dataset is now ready for encoding, scaling, and model training.