# Day 4 - Data Analysis with Pandas

## Objectives
- Import Pandas
- Load Dataset
- Explore Data
- Understand Dataset Structure
- Perform Basic Data Analysis

In [2]:
import pandas as pd 
import numpy as np 

print("Pandas Version : ", pd.__version__)

Pandas Version :  3.0.3

In [106]:
#creating a sample dataset
student_data = {
    'student_name': ['Alice', 'Bob', 'Charlie', 'David','Aman', 'karan', 'Ankita','prince','Priya','Anjali','Anita','Aniket','Meera','Hina','Palak','Harshita', 'Rahul','Rohit', 'Preeti', 'Chahana', 'Sohan'],
    'study_hours': [5,7, 6, 7, 7, 5,  6, 6, 4,   4, 3, 2,   4 , 8, 3, 5, 5, 2, 2, 8, 5,],
    'Score': [85, 95, 80, 95, 77, 65, 99, 95, 60, 67,57, 60, 73,80,48,40,75,46, 49, 88, 78]
}
df = pd.DataFrame(student_data)
df

   student_name  study_hours  Score
0         Alice            5     85
1           Bob            7     95
2       Charlie            6     80
3         David            7     95
4          Aman            7     77
5         karan            5     65
6        Ankita            6     99
7        prince            6     95
8         Priya            4     60
9        Anjali            4     67
10        Anita            3     57
11       Aniket            2     60
12        Meera            4     73
13         Hina            8     80
14        Palak            3     48
15     Harshita            5     40
16        Rahul            5     75
17        Rohit            2     46
18       Preeti            2     49
19      Chahana            8     88
20        Sohan            5     78

In [107]:
#Display First and Last Records of the dataset
print("First 4 rows of the dataset : \n", df.head(4))
print("\nLast 4 rows of the dataset : \n", df.tail(4))

First 4 rows of the dataset :
   student_name  study_hours  Score
0        Alice            5     85
1          Bob            7     95
2      Charlie            6     80
3        David            7     95

Last 4 rows of the dataset :
    student_name  study_hours  Score
17        Rohit            2     46
18       Preeti            2     49
19      Chahana            8     88
20        Sohan            5     78

In [108]:
#Dataset Information
information = df.info()
print(information)

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_name  21 non-null     str
 1   study_hours   21 non-null     int64
 2   Score         21 non-null     int64
dtypes: int64(2), str(1)
memory usage: 636.0 bytes
None

In [109]:
print("Shape of dataset ,rows and columns : ", df.shape)

Shape of dataset ,rows and columns :  (21, 3)

In [110]:
print(df.columns)

Index(['student_name', 'study_hours', 'Score'], dtype='str')

In [111]:
print(df.shape[0])

21

In [112]:
df.dtypes

student_name      str
study_hours     int64
Score           int64
dtype: object

In [113]:
#Statistical values of the dataset
df.describe()

       study_hours      Score
count    21.000000  21.000000
mean      4.952381  72.000000
std       1.883512  17.793257
min       2.000000  40.000000
25%       4.000000  60.000000
50%       5.000000  75.000000
75%       6.000000  85.000000
max       8.000000  99.000000

In [114]:
#select columns
df[['student_name']]

   student_name
0         Alice
1           Bob
2       Charlie
3         David
4          Aman
5         karan
6        Ankita
7        prince
8         Priya
9        Anjali
10        Anita
11       Aniket
12        Meera
13         Hina
14        Palak
15     Harshita
16        Rahul
17        Rohit
18       Preeti
19      Chahana
20        Sohan

In [115]:
df[['student_name', 'Score']]

   student_name  Score
0         Alice     85
1           Bob     95
2       Charlie     80
3         David     95
4          Aman     77
5         karan     65
6        Ankita     99
7        prince     95
8         Priya     60
9        Anjali     67
10        Anita     57
11       Aniket     60
12        Meera     73
13         Hina     80
14        Palak     48
15     Harshita     40
16        Rahul     75
17        Rohit     46
18       Preeti     49
19      Chahana     88
20        Sohan     78

In [116]:
df.iloc[2]

student_name    Charlie
study_hours           6
Score                80
Name: 2, dtype: object

In [117]:
df.iloc[0:5, 0:2]

  student_name  study_hours
0        Alice            5
1          Bob            7
2      Charlie            6
3        David            7
4         Aman            7

In [118]:
df.iloc[1:4]

  student_name  study_hours  Score
1          Bob            7     95
2      Charlie            6     80
3        David            7     95

In [119]:
#Student scoring above 50
high_scores = df[df['Score'] >= 70]
high_scores

   student_name  study_hours  Score
0         Alice            5     85
1           Bob            7     95
2       Charlie            6     80
3         David            7     95
4          Aman            7     77
6        Ankita            6     99
7        prince            6     95
12        Meera            4     73
13         Hina            8     80
16        Rahul            5     75
19      Chahana            8     88
20        Sohan            5     78

In [120]:
#sorting of students according to scores
df.sort_values(by = 'Score', ascending = False)

   student_name  study_hours  Score
6        Ankita            6     99
3         David            7     95
1           Bob            7     95
7        prince            6     95
19      Chahana            8     88
0         Alice            5     85
2       Charlie            6     80
13         Hina            8     80
20        Sohan            5     78
4          Aman            7     77
16        Rahul            5     75
12        Meera            4     73
9        Anjali            4     67
5         karan            5     65
8         Priya            4     60
11       Aniket            2     60
10        Anita            3     57
18       Preeti            2     49
14        Palak            3     48
17        Rohit            2     46
15     Harshita            5     40

In [121]:
#Adding new column of result
df["Result"] = np.where(df["Score"] >= 60 , "PASS" ,"FAIL")
df

   student_name  study_hours  Score Result
0         Alice            5     85   PASS
1           Bob            7     95   PASS
2       Charlie            6     80   PASS
3         David            7     95   PASS
4          Aman            7     77   PASS
5         karan            5     65   PASS
6        Ankita            6     99   PASS
7        prince            6     95   PASS
8         Priya            4     60   PASS
9        Anjali            4     67   PASS
10        Anita            3     57   FAIL
11       Aniket            2     60   PASS
12        Meera            4     73   PASS
13         Hina            8     80   PASS
14        Palak            3     48   FAIL
15     Harshita            5     40   FAIL
16        Rahul            5     75   PASS
17        Rohit            2     46   FAIL
18       Preeti            2     49   FAIL
19      Chahana            8     88   PASS
20        Sohan            5     78   PASS

In [122]:
#Average score
average = df['Score'].mean()
print("Average Score : ",average)

Average Score :  72.0

In [123]:
#Highest and Lowest marks
print("Highest Score : ",df["Score"].max())
print("Lowest Score : " ,df["Score"].min())

Highest Score :  99
Lowest Score :  40

In [125]:
#Top performer
top_student = df.loc[df["Score"].idxmax()]
top_student

student_name    Ankita
study_hours          6
Score               99
Result            PASS
Name: 6, dtype: object

In [ ]:
#Total no. of students passed and failed
df["Result"].value_counts()

Result
PASS    16
FAIL     5
Name: count, dtype: int64